### ISSUE TITLE
 Moralis WebGL Template disappeared in 1.2.0

### ISSUE THREAD

**Issue by ioioio8888** [ethereum-boilerplate/web3-unity-boilerplate#102]
After importing the Unity package, the Moralis WebGL Template is not showed up in the selection.
which I think it is not included in the unity package in 1.2.0
![image](https://user-images.githubusercontent.com/19797490/170870217-0ddf346b-bd8f-4455-aae6-abd2c8893758.png)

**Comment by KoenRijpstra** [comment]
Hi @ioioio8888 thanks for you question. The WebGLTemplates can now be found in the editor under `Packages\Moralis Web3 Unity SDK\Resources\WebGLTemplates\`.  Sorry for not being clear about this and we will update this in our documentation. Have a great day!
