### ISSUE TITLE
Please release this as a UPM-compatible package

### ISSUE THREAD

**Issue by Vivraan** [ethereum-boilerplate/web3-unity-boilerplate#42]
Reference: https://forum.moralis.io/t/ethereum-unity3d-boilerplate-questions/4553/307?u=vivraan

This is a request to consider making this a UPM package, which makes updates and dependencies more streamlined, instead of having copies of dependencies which may not be desirable, such as TextMeshPro.

The following is a weak argument: I already maintain my project code as defined with separate Assembly Definition files, which makes working with this package painful since I have to set it up manually each time I want to use it. I've also created a project which contains this project's contents in a UPM compatible package which I use in multiple projects, making it easy to manage.

**Comment by Vivraan** [comment]
For reference, Cinemachine:
![image](https://user-images.githubusercontent.com/12777564/153815500-cfb6aa08-370a-4453-821c-4f43397a2ef3.png)

**Comment by KoenRijpstra** [comment]
With the release of version 1.2.0 there is now a UPM-compatible package 〽️ 

#### 📄 Setup via Git URL
1. Select menu _Window -> Package Manager_
2. Add package from Git URL: `https://github.com/MoralisWeb3/web3-unity-sdk.git`
3. Select the Moralis Web3 Unity SDK and click on the _Install_ button.
4. OPTIONAL - install the demo.

#### 📄 Setup via UPM Package
1. Select menu _Window -> Package Manager_
3. Open Settings and select _Advanced Project Settings_
4. In the _Package Manager_ section add a scoped registry entry for moralis on npmjs
NAME: `npmjs`
URL: `https://registry.npmjs/org`
SCOPE(s): `io.moralis`
5. Click on the _Save_ button and close the _Project Settings_ window.
6. In _Package Manager_ select _My Registries_ from the location dropdown.
7. Select the Moralis Web3 Unity SDK and click on the _Install_ button.
8. OPTIONAL - install the demo.
