### ISSUE TITLE
With Unity 2020.3.30 Newtonsoft Missing

### ISSUE THREAD

**Issue by xactant** [ethereum-boilerplate/web3-unity-boilerplate#71]
The Newtonsoft library was automatically included in previous Unity versions.

Many users have reported that starting around 2020.3.28 (I observed this with Unity 2020.3.30) the Newtonsoft package was no longer automatically included.

UPM package.json with Newtonsoft dependency listed should solve this. 

Accelerate the move to Unity Package Manager compatibility to meet this need.

**Comment by KoenRijpstra** [comment]
If you need a work around you can add the package this way:
https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Install-official-via-UPM#installing-the-package-via-manifestjson

**Comment by KoenRijpstra** [comment]
Fixed in the new 1.2.0 release 🥳
